apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-frontend
  namespace: default
  labels:
    app: music-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-frontend
  template:
    metadata:
      labels:
        app: music-frontend
    spec:
      containers:
      - name: frontend
        image: kl2300033362/mirchiweb-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
